const mongoose = require('mongoose');

const Character = require('../../../modules/characters/character.model');
const Movie = require('../../../modules/wiki/models/movie.model');

let movieId;

beforeEach(async () => {
    const movie = await Movie.create({
        title: 'Test Movie', synopsis: 'A story.', slug: 'test-movie',
    });
    movieId = movie._id;
});

const validChar = () => ({
    name: 'Kaguya',
    role: 'Protagonist',
    movie: movieId,
});

describe('Character Model', () => {
    describe('Validations', () => {
        it('should create a valid character', async () => {
            const char = await Character.create(validChar());
            expect(char._id).toBeDefined();
            expect(char.name).toBe('Kaguya');
            expect(char.slug).toBeDefined(); // auto-generated by mongoose-slug-updater
        });

        it('should require name', async () => {
            await expect(
                Character.create({ role: 'Protagonist', movie: movieId })
            ).rejects.toThrow();
        });

        it('should require movie reference', async () => {
            await expect(
                Character.create({ name: 'Test', role: 'Protagonist' })
            ).rejects.toThrow();
        });

        it('should only allow valid roles', async () => {
            const char = await Character.create({
                ...validChar(), name: 'Villain', role: 'Antagonist',
            });
            expect(char.role).toBe('Antagonist');

            await expect(
                Character.create({ ...validChar(), name: 'Bad', role: 'InvalidRole' })
            ).rejects.toThrow();
        });

        it('should accept all valid role values', async () => {
            const roles = ['Protagonist', 'Supporting', 'Antagonist', 'Cameo'];
            for (const role of roles) {
                const char = await Character.create({
                    name: `Char-${role}`, role, movie: movieId,
                });
                expect(char.role).toBe(role);
            }
        });

        it('should auto-generate slug from name', async () => {
            const char = await Character.create(validChar());
            expect(char.slug).toBe('kaguya');
        });

        it('should generate unique slug with suffix for duplicate names', async () => {
            const char1 = await Character.create(validChar());
            const char2 = await Character.create(validChar());
            // mongoose-slug-updater appends a random suffix for duplicates
            expect(char1.slug).toBe('kaguya');
            expect(char2.slug).not.toBe('kaguya');
            expect(char2.slug).toMatch(/^kaguya-/); // e.g. kaguya-A1sO4tXXW
        });
    });

    describe('Nested Schema Fields', () => {
        it('should store description subdocument', async () => {
            const char = await Character.create({
                ...validChar(),
                description: {
                    summary: 'Moon princess',
                    personality: 'Kind and brave',
                    appearance: {
                        realWorld: 'Long dark hair',
                        tsukuyomi: 'Glowing white dress',
                    },
                },
            });
            expect(char.description.summary).toBe('Moon princess');
            expect(char.description.appearance.tsukuyomi).toBe('Glowing white dress');
        });

        it('should store origin subdocument', async () => {
            const char = await Character.create({
                ...validChar(),
                origin: { location: 'Moon', birthday: 'Unknown', race: 'Celestial' },
            });
            expect(char.origin.location).toBe('Moon');
            expect(char.origin.race).toBe('Celestial');
        });

        it('should store abilities array', async () => {
            const char = await Character.create({
                ...validChar(),
                abilities: [
                    { skillName: 'Moonlight', type: 'Active', effect: ['Heal', 'Shield'] },
                    { skillName: 'Gravity', type: 'Passive', effect: ['Float'] },
                ],
            });
            expect(char.abilities).toHaveLength(2);
            expect(char.abilities[0].skillName).toBe('Moonlight');
            expect(char.abilities[0].effect).toContain('Heal');
        });

        it('should only allow valid ability types', async () => {
            await expect(
                Character.create({
                    ...validChar(), name: 'Bad Ability',
                    abilities: [{ skillName: 'X', type: 'SuperMove', effect: [] }],
                })
            ).rejects.toThrow();
        });

        it('should store image array', async () => {
            const char = await Character.create({
                ...validChar(),
                image: [
                    { url: 'https://img.com/1.jpg', public_id: 'img1' },
                    { url: 'https://img.com/2.jpg', public_id: 'img2' },
                ],
            });
            expect(char.image).toHaveLength(2);
        });

        it('should store relationships array', async () => {
            const char2 = await Character.create({
                name: 'Iroha', role: 'Supporting', movie: movieId,
            });
            const char = await Character.create({
                ...validChar(),
                relationships: [{
                    targetId: char2._id,
                    relationType: 'friend',
                    description: 'Close companion',
                }],
            });
            expect(char.relationships).toHaveLength(1);
            expect(char.relationships[0].relationType).toBe('friend');
        });
    });

    describe('Indexes', () => {
        it('should have text index on name and description.summary', async () => {
            const indexes = Character.schema.indexes();
            const textIndex = indexes.find(([fields]) =>
                fields.name === 'text' || fields['description.summary'] === 'text'
            );
            expect(textIndex).toBeDefined();
        });

        it('should have index on role', async () => {
            const indexes = Character.schema.indexes();
            const roleIndex = indexes.find(([fields]) => fields.role);
            expect(roleIndex).toBeDefined();
        });

        it('should have index on movie', async () => {
            const indexes = Character.schema.indexes();
            const movieIndex = indexes.find(([fields]) => fields.movie);
            expect(movieIndex).toBeDefined();
        });
    });
});
