const Soundtrack = require('./sound-track.model');
const { WikiError, ValidationError, NotFoundError } = require('../../errors');

/**
 * Helper: Formats a track document including the lyrics and virtuals
 */
const formatTrack = (track) => {
    if (!track) return null;
    return {
        _id: track._id,
        trackNumber: track.trackNumber,
        title: track.title,
        vocal: track.vocal,
        producer: track.producer,
        trackType: track.trackType,
        youtubeId: track.youtubeId,
        startTime: track.startTime,
        endTime: track.endTime,
        embedUrl: track.embedUrl, // Virtual generated by Mongoose schema
        coverImage: track.coverImage?.url ?? null,
        lyrics: {
            original: track.lyrics?.original ?? "",
            romaji: track.lyrics?.romaji ?? "",
            translation: track.lyrics?.translation ?? "",
            synced: track.lyrics?.synced ?? [] // For Karaoke-style UI
        },
        movie: track.movie
    };
};

/**
 * Get all tracks for a movie, sorted by the trackNumber index
 */
const fetchTracksByMovie = async (movieId) => {
    if (!movieId) {
        throw new ValidationError('movieId query parameter is required.');
    }
    const tracks = await Soundtrack.find({ movie: movieId }).sort({ trackNumber: 1 });
    return tracks.map(formatTrack);
};

/**
 * Main logic for playback navigation (Sequential, Shuffle, Infinite)
 */
const getNextTrackLogic = async (params) => {
    const { currentTrackId, mode, movieId } = params;

    if (!currentTrackId || !mode || !movieId) {
        throw new ValidationError('currentTrackId, mode, and movieId are required.');
    }

    const currentTrack = await Soundtrack.findOne({ _id: currentTrackId, movie: movieId });
    if (!currentTrack) {
        throw new NotFoundError('Track not found in this movie context.');
    }

    // 1. Mode: INFINITE (Loops the same song)
    if (mode === 'infinite') {
        return { mode, track: formatTrack(currentTrack), restart: true };
    }

    const totalTracks = await Soundtrack.countDocuments({ movie: movieId });
    if (totalTracks === 1) {
        return { mode, track: formatTrack(currentTrack), restart: true };
    }

    // 2. Mode: SHUFFLE (Randomized excluding current)
    if (mode === 'shuffle') {
        const [randomDoc] = await Soundtrack.aggregate([
            { $match: { movie: currentTrack.movie, _id: { $ne: currentTrack._id } } },
            { $sample: { size: 1 } }
        ]);
        if (!randomDoc) {
            // fallback if aggregate fails for some reason
            return { mode, track: formatTrack(currentTrack), restart: true };
        }
        const randomTrack = await Soundtrack.findById(randomDoc._id);
        return { mode, track: formatTrack(randomTrack) };
    }

    // 3. Mode: SEQUENTIAL (Next number or wrap to start)
    if (mode === 'sequential') {
        let nextTrack = await Soundtrack.findOne({
            movie: movieId,
            trackNumber: currentTrack.trackNumber + 1
        });

        // If no "next" track number, wrap back to the beginning (trackNumber 1 or 0)
        if (!nextTrack) {
            nextTrack = await Soundtrack.findOne({ movie: movieId }).sort({ trackNumber: 1 });
        }

        return {
            mode,
            track: formatTrack(nextTrack),
            wrapped: nextTrack.trackNumber <= currentTrack.trackNumber
        };
    }

    throw new ValidationError('Invalid playback mode.');
};

module.exports = {
    fetchTracksByMovie,
    getNextTrackLogic,
};
