const Soundtrack = require('./sound-track.model')
const { WikiError, ValidationError, NotFoundError } = require('../../errors')

const normalizeMovie = (movie) => {
  if (!movie || !movie.title) return null

  return {
    _id: String(movie._id),
    title: movie.title,
  }
}

/**
 * Helper: Formats a track document including the lyrics and virtuals
 */
const formatTrack = (track) => {
  if (!track) return null
  return {
    _id: track._id,
    slug: track.slug,
    trackNumber: track.trackNumber,
    title: track.title,
    vocal: track.vocal,
    producer: track.producer,
    trackType: track.trackType,
    youtubeId: track.youtubeId,
    startTime: track.startTime,
    endTime: track.endTime,
    embedUrl: track.embedUrl, // Virtual generated by Mongoose schema
    coverImage: track.coverImage?.url ?? null,
    officialUrl: track.officialUrl ?? [],
    lyrics: {
      romaji: track.lyrics?.romaji ?? '',
      translation: track.lyrics?.translation ?? '',
      translator: track.lyrics?.translator ?? '',
      source: track.lyrics?.source ?? '',
      synced: track.lyrics?.synced ?? [], // For Karaoke-style UI
    },
    movie: normalizeMovie(track.movie),
  }
}

/**
 * Get all tracks for a movie, sorted by the trackNumber index
 */
const fetchTracksByMovie = async (movieId) => {
  if (!movieId) {
    throw new ValidationError('movieId query parameter is required.')
  }
  const safeMovieId = String(movieId)
  const tracks = await Soundtrack.find({ movie: safeMovieId })
    .populate('movie', 'title')
    .sort({
      trackNumber: 1,
    })
  return tracks.map(formatTrack)
}

/**
 * Main logic for playback navigation (Sequential, Shuffle, Infinite)
 */
const getNextTrackLogic = async (params) => {
  const { currentTrackId, mode, movieId } = params

  if (!currentTrackId || !mode || !movieId) {
    throw new ValidationError('currentTrackId, mode, and movieId are required.')
  }

  const safeTrackId = String(currentTrackId)
  const safeMovieId = String(movieId)

  const currentTrack = await Soundtrack.findOne({
    _id: safeTrackId,
    movie: safeMovieId,
  }).populate('movie', 'title')
  if (!currentTrack) {
    throw new NotFoundError('Track not found in this movie context.')
  }

  // 1. Mode: INFINITE (Loops the same song)
  if (mode === 'infinite') {
    return { mode, track: formatTrack(currentTrack), restart: true }
  }

  const totalTracks = await Soundtrack.countDocuments({ movie: movieId })
  if (totalTracks === 1) {
    return { mode, track: formatTrack(currentTrack), restart: true }
  }

  // 2. Mode: SHUFFLE (Randomized excluding current)
  if (mode === 'shuffle') {
    const currentMovieId = currentTrack.movie?._id ?? safeMovieId
    const [randomDoc] = await Soundtrack.aggregate([
      { $match: { movie: currentMovieId, _id: { $ne: currentTrack._id } } },
      { $sample: { size: 1 } },
    ])
    if (!randomDoc) {
      // fallback if aggregate fails for some reason
      return { mode, track: formatTrack(currentTrack), restart: true }
    }
    const randomTrack = await Soundtrack.findById(randomDoc._id).populate(
      'movie',
      'title'
    )
    return { mode, track: formatTrack(randomTrack) }
  }

  // 3. Mode: SEQUENTIAL (Next number or wrap to start)
  if (mode === 'sequential') {
    let nextTrack = await Soundtrack.findOne({
      movie: movieId,
      trackNumber: currentTrack.trackNumber + 1,
    }).populate('movie', 'title')

    // If no "next" track number, wrap back to the beginning (trackNumber 1 or 0)
    if (!nextTrack) {
      nextTrack = await Soundtrack.findOne({ movie: movieId })
        .populate('movie', 'title')
        .sort({
          trackNumber: 1,
        })
    }

    return {
      mode,
      track: formatTrack(nextTrack),
      wrapped: nextTrack.trackNumber <= currentTrack.trackNumber,
    }
  }

  throw new ValidationError('Invalid playback mode.')
}

/**
 * Fetch single track by slug with regex fallback (matches title if slug not found)
 */
const fetchTrackBySlug = async (slug) => {
  let track = await Soundtrack.findOne({ slug }).populate('movie', 'title')

  if (!track) {
    // Regex fallback: convert hyphens back to spaces/hyphens pattern
    const escapedSlug = slug.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const titlePattern = escapedSlug.replace(/-/g, '[\\s\\-]')
    track = await Soundtrack.findOne({
      title: { $regex: new RegExp(`^${titlePattern}$`, 'i') },
    }).populate('movie', 'title')
  }

  if (!track) {
    throw new NotFoundError(`No soundtrack found with slug: ${slug}`)
  }

  return formatTrack(track)
}

module.exports = {
  fetchTracksByMovie,
  getNextTrackLogic,
  fetchTrackBySlug,
}
